### ISSUE TITLE
iPhone / iPad Sweet Alert 2 blank screen

### ISSUE THREAD

**Issue by csuzlee13** [limonte/sweetalert2#473]
Hi,

I'm using sweet alert 2 in a symfony project and I get back a blank screen on iPhones and iPads, when the alert should pop up. The code is the following:

    function emlmpurchaseuserFormBeforeSubmit(formData, jqForm, options) {
        if (!package_user_form_can_submit) {
            swal({
                title: '<?php echo __('Data Verfication', array(), 'sf_eromu_mlm');?>',
                text: '<?php echo __('The data are correct!', array(), 'sf_eromu_mlm');?>',
                type: 'warning',
                showCancelButton: true,
                confirmButtonText: '<?php echo __('Yes', array(), 'sf_eromu_mlm');?>',
                cancelButtonText: '<?php echo __('No, cancel!', array(), 'sf_eromu_mlm');?>',
            }).then(function () {
                package_user_form_can_submit = true;
                $('#emlmedituser_form').submit();
            }, function (dismiss) {
            });
            return false;
        } else {
            $('#emlmedituser_form input[type="submit"]').attr('disabled', 'disabled');
            package_user_form_can_submit = false;
            return true;
        }

I'm using the newest version of sweetalert2 and bootstrap also.

**Comment by limonte** [comment]
>For bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by limonte** [comment]
Reply with jsfiddle if needed and I will reopen this issue

**Comment by csuzlee13** [comment]
Sorry, the code was too complicated to implement into jsfiddle. Anyway I found the problem. On iOS the body.swal2-iosfix css class got top: -2470px property. Now I fixed it with a "top: 0px !important" solution in the sweetalert2.min.css but I think the problem is in the js.

**Comment by limonte** [comment]
@csuzlee13 we are indeed setting the `top` property to `body` for `iOS`, 

here's why: https://github.com/limonte/sweetalert2/issues/302
here's how: https://github.com/limonte/sweetalert2/commit/4a2d36b494fbae879c9a17f92af90cb61f03b4d5

It will be really great if you could find time to reproduce this issue in jsfiddle. I'm pretty sure it's related to your application layout and the SweeAlert2 somehow conflicting with it.

Thanks for using the SweeAlert2!

**Comment by corydozen** [comment]
For me, this solved it:
```
body {
  position: static !important;
}
```

**Comment by bverussa** [comment]
I got the same error. I fixed it changing the position to relative. But if you remove the class swal2-iosfix works too.

**Comment by vjoao** [comment]
Great... you do a `fix` for one particular use case and break all the others.

**Comment by socendani** [comment]
Thanks!!!
SweetAlert2 + ionic3  .. content (in background) under the backdrop hidden. With  @corydozen solution.. perfect for me.. thanks!..

**Comment by kimyu92** [comment]
@limonte i have also run into this problem, still not sure whether it is an iOS bug or bug from sweetalert
